apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vertexai-gemini.name" . }}
  labels:
    {{- include "vertexai-gemini.labels" . | nindent 4 }}
  annotations:
    {{- include "vertexai-gemini.argocd-syncwave" . | nindent 4 }}
type: "Opaque"
data:
  vertexai:
    {{ .Values.vertexai.credentials }}
