nameOverride: streams-console

namespace: 
subdomain:

kafka:
  name: kafka
  authentication:
    saslMechanism: SCRAM-SHA-512
    securityProtocol: SASL_PLAINTEXT
  authorization: simple

argocd:
  syncwave:
    enabled: true
    console: "1"
