apiVersion: v1
kind: Secret
metadata:
  name: {{ include "finance-mcp.name" . }}
  labels:
    {{- include "finance-mcp.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-

    quarkus.rest-client.finance.url={{ .Values.rest.finance.url }}
