apiVersion: v1
kind: Secret
metadata:
  name: {{ include "finance-ai.name" . }}
  labels:
    {{- include "finance-ai.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-

    kafka.bootstrap.servers={{ .Values.kafka.bootstrapServer }}

    {{- if .Values.kafka.securityProtocol }}
    mp.messaging.connector.smallrye-kafka.security.protocol={{ .Values.kafka.securityProtocol }}
    {{- end }}
    {{- if .Values.kafka.saslMechanism }}
    mp.messaging.connector.smallrye-kafka.sasl.mechanism={{ .Values.kafka.saslMechanism }}
    {{- end }}

    {{- if eq .Values.kafka.saslMechanism "PLAIN" }}
    mp.messaging.connector.smallrye-kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
      username="{{ .Values.kafka.clientId }}" \
      password="{{ .Values.kafka.clientSecret }}" ;
    {{- end }}
    {{- if eq .Values.kafka.saslMechanism "SCRAM-SHA-512" }}
    mp.messaging.connector.smallrye-kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
      username="{{ .Values.kafka.clientId }}" \
      password="{{ .Values.kafka.clientSecret }}" ;
    {{- end }}

    mp.messaging.incoming.finance.topic={{ .Values.kafka.topic.finance }}
    mp.messaging.incoming.finance.group.id={{ .Values.kafka.consumerGroup.finance }}

    mp.messaging.outgoing.outflow.topic={{ .Values.kafka.topic.outflow }}
    mp.messaging.outgoing.error.topic={{ .Values.kafka.topic.error }}

    quarkus.langchain4j.openai.chat-model.model-name={{ .Values.llm.modelName }}
    quarkus.langchain4j.openai.api-key={{ .Values.llm.apiKey }}
    quarkus.langchain4j.openai.base-url={{ .Values.llm.baseUrl }}

    quarkus.langchain4j.mcp.finance.url={{ .Values.mcp.finance.url }}
    quarkus.langchain4j.mcp.finance.log-requests={{ .Values.mcp.finance.log.requests }}
    quarkus.langchain4j.mcp.finance.log-responses={{ .Values.mcp.finance.log.responses }}
