apiVersion: v1
kind: Secret
metadata:
  name: {{ include "support-ai.name" . }}
  labels:
    {{- include "support-ai.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-

    kafka.bootstrap.servers={{ .Values.kafka.bootstrapServer }}

    {{- if .Values.kafka.securityProtocol }}
    mp.messaging.connector.smallrye-kafka.security.protocol={{ .Values.kafka.securityProtocol }}
    {{- end }}
    {{- if .Values.kafka.saslMechanism }}
    mp.messaging.connector.smallrye-kafka.sasl.mechanism={{ .Values.kafka.saslMechanism }}
    {{- end }}

    {{- if eq .Values.kafka.saslMechanism "PLAIN" }}
    mp.messaging.connector.smallrye-kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
      username="{{ .Values.kafka.clientId }}" \
      password="{{ .Values.kafka.clientSecret }}" ;
    {{- end }}
    {{- if eq .Values.kafka.saslMechanism "SCRAM-SHA-512" }}
    mp.messaging.connector.smallrye-kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
      username="{{ .Values.kafka.clientId }}" \
      password="{{ .Values.kafka.clientSecret }}" ;
    {{- end }}

    mp.messaging.incoming.support.topic={{ .Values.kafka.topic.support }}
    mp.messaging.incoming.support.group.id={{ .Values.kafka.consumerGroup.support }}

    mp.messaging.outgoing.outflow.topic={{ .Values.kafka.topic.outflow }}
    mp.messaging.outgoing.error.topic={{ .Values.kafka.topic.error }}

    langchain4j.openai.chat.base-url={{ .Values.llm.baseUrl }}
    langchain4j.openai.chat.model-name={{ .Values.llm.modelName }}
    langchain4j.openai.chat.api-key={{ .Values.llm.apiKey }}
    langchain4j.openai.chat.temperature={{ .Values.llm.temperature }}
    langchain4j.openai.chat.timeout={{ .Values.llm.timeout }}
    langchain4j.openai.chat.log-requests={{ .Values.llm.log.requests }}
    langchain4j.openai.chat.log-responses={{ .Values.llm.log.responses }}

    langchain4j.openai.embedding.base-url={{ .Values.embedding.baseUrl }}
    langchain4j.openai.embedding.model-name={{ .Values.embedding.modelName }}
    langchain4j.openai.embedding.api-key={{ .Values.embedding.apiKey }}
    langchain4j.openai.embedding.timeout={{ .Values.embedding.timeout }}
    langchain4j.openai.embedding.log-requests={{ .Values.embedding.log.requests }}
    langchain4j.openai.embedding.log-responses={{ .Values.embedding.log.responses }}

    milvus.uri={{ .Values.milvus.url }}
    milvus.username={{ .Values.milvus.username }}
    milvus.password={{ .Values.milvus.password }}
    milvus.collection-name={{ .Values.milvus.collection }}
    milvus.dimension={{ .Values.milvus.dimension }}

    embedding.max-results={{ .Values.retrieval.maxResults }}
    embedding.min-score={{ .Values.retrieval.minScore }}
