apiVersion: v1
kind: Secret
metadata:
  name: {{ include "website-mcp.name" . }}
  labels:
    {{- include "website-mcp.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-

